# Generated by Django 4.1.2 on 2022-11-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='project name')),
                ('repo_url', models.URLField(blank=True, verbose_name='link to repository')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='project participants')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='note title')),
                ('content', models.TextField(verbose_name='note content')),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TD', 'to do'), ('PR', 'in progress'), ('RW', 'in review'), ('CL', 'closed'), ('BL', 'blocked')], default='TD', max_length=2, verbose_name='note status')),
                ('by_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_project', to='todoapp.project')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
